### ISSUE TITLE
uamqp version 1.6.0 gives error when installing.

### ISSUE THREAD

**Issue by amir-kashi** [elexon-data/iris-clients#24]
Update `uamqp` version

The version 1.6.0 gives the following error when installing the requirements:

```
 ERROR: Failed building wheel for uamqp
 Failed to build uamqp
 ERROR: Could not build wheels for uamqp, which is required to install pyproject.toml-based projects
```

However the newer version (uamqp==1.6.9) is fine.

Machine tested on:
Windows 11
VS Code
Python 3.11

**Comment by ZakCannon** [comment]
Hi Amir, just letting you know we've seen this. We'll look at updating the packages here shortly, and link that PR to this issue. In the meantime, I'll leave this issue up for visibility, for anyone else having this issue.
