### ISSUE TITLE
Python connection issues

### ISSUE THREAD

**Issue by BenjaminWatts** [elexon-data/iris-clients#8]
I've copied the Python example from the repo and keep getting this log / stack trace when trying to connect. It looks like the credentials and token are ok - and (though I haven't copied it), I can see if gets a token successfully. However, it seems to be erroring when securing a connection to the AMPQ client on the server. The file path 'Users/runner/work' in particular looks very much like a path on the server, and not on my local client (which is a mac).

Any suggestions. As I haven't connected for a while, it crossed my mind that the queue might be gummed up with too much of a backlog?

`INFO:azure.identity._internal.get_token_mixin:ClientSecretCredential.get_token succeeded
INFO:uamqp.connection:Connection b'SBReceiver-980cc67c-e654-4eea-8e1c-9d84a1117537' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
INFO:uamqp.connection:Connection b'SBReceiver-980cc67c-e654-4eea-8e1c-9d84a1117537' state changed from <ConnectionState.START: 0> to <ConnectionState.END: 13>
INFO:uamqp.connection:Connection with ID b'SBReceiver-980cc67c-e654-4eea-8e1c-9d84a1117537' unexpectedly in an error state. Closing: False, Error: None
INFO:uamqp.c_uamqp:b'AMQP management instance not open' (b'/Users/runner/work/1/s/src/vendor/azure-uamqp-c/src/amqp_management.c':b'amqp_management_close':1061)
INFO:uamqp.c_uamqp:CBS for connection b'SBReceiver-980cc67c-e654-4eea-8e1c-9d84a1117537' completed opening with status: 2
DEBUG:uamqp.c_uamqp:Wrapping value type: <AMQPType.CompositeType: 23>
DEBUG:uamqp.c_uamqp:Wrapping value type: <AMQPType.CompositeType: 23>
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'DictValue'
DEBUG:uamqp.c_uamqp:Destroying 'DictValue'
INFO:uamqp.receiver:Message receiver b'receiver-link-a3bd7291-6c85-400f-9be0-ed78227c2de0' state changed from <MessageReceiverState.Idle: 1> to <MessageReceiverState.Opening: 2> on connection: b'SBReceiver-980cc67c-e654-4eea-8e1c-9d84a1117537'
INFO:uamqp.receiver:Receiver link failed to open - expecting to receive DETACH frame.
WARNING:uamqp.connection:ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')`

**Comment by BenjaminWatts** [comment]
I think in particular the 'AMQP management instance not open' seems quite prescient!

**Comment by ZakCannon** [comment]
Closing as this issue is quite old - please do re-open and we can investigate if it's still an issue
